### ISSUE TITLE
Hour Preceding Zero

### ISSUE THREAD

**Issue by ljschoepke** [jackson-nestelroad/christ-centered-2.0#2]
Please seriously consider removing the preceding zero from the hour time display.

ie. Time should be shown as 1 00 00 through 9 59 59.  (Not 01 00 00 and 09 59 59)

Thank  you.

**Comment by jackson-nestelroad** [comment]
Hello. Thanks so much for using the extension! I've added a new option in the left-hand-side menu for toggling the leading zero on the hour display.

<img width="244" alt="image" src="https://github.com/jackson-nestelroad/christ-centered-2.0/assets/40396320/d79ed654-bc95-4269-b6c0-b224208a4f36">

This feature should be available in version 2.2.2. I will work on getting it reviewed and published for both Chrome and Firefox this week. Once published, your extension should update automatically. I'll close this feature request as soon as it is verified to be published. Thank you!

**Comment by jackson-nestelroad** [comment]
Version 2.2.2 is live on Chrome and Firefox. I hope this works well for you!
